pages = [{"l":"index.html#","e":false,"i":"","n":"root","t":"root","d":"","k":"static","x":""},
{"l":"kuram.html#","e":false,"i":"","n":"kuram","t":"kuram","d":"","k":"package","x":""},
{"l":"kuram/Monoid.html#","e":false,"i":"","n":"Monoid","t":"Monoid[T] extends Semigroup[T]","d":"kuram","k":"trait","x":""},
{"l":"kuram/Monoid.html#empty-0","e":false,"i":"","n":"empty","t":"empty: T","d":"kuram.Monoid","k":"def","x":""},
{"l":"kuram/Monoid$.html#","e":false,"i":"","n":"Monoid","t":"Monoid","d":"kuram","k":"object","x":""},
{"l":"kuram/Monoid$.html#apply-961","e":false,"i":"","n":"apply","t":"apply[T](using instance: Monoid[T]): Monoid[T]","d":"kuram.Monoid","k":"def","x":""},
{"l":"kuram/MonoidInstances$.html#","e":false,"i":"","n":"MonoidInstances","t":"MonoidInstances","d":"kuram","k":"object","x":""},
{"l":"kuram/MonoidInstances$.html#given_Monoid_Int-0","e":false,"i":"","n":"given_Monoid_Int","t":"given_Monoid_Int: given_Monoid_Int","d":"kuram.MonoidInstances","k":"given","x":""},
{"l":"kuram/MonoidInstances$.html#given_Monoid_List-c1e","e":false,"i":"","n":"given_Monoid_List","t":"given_Monoid_List[A]: given_Monoid_List[A]","d":"kuram.MonoidInstances","k":"given","x":""},
{"l":"kuram/MonoidInstances$.html#given_Monoid_String-0","e":false,"i":"","n":"given_Monoid_String","t":"given_Monoid_String: given_Monoid_String","d":"kuram.MonoidInstances","k":"given","x":""},
{"l":"kuram/MonoidInstances$$given_Monoid_Int$.html#","e":false,"i":"","n":"given_Monoid_Int","t":"given_Monoid_Int extends Monoid[Int]","d":"kuram.MonoidInstances","k":"object","x":""},
{"l":"kuram/MonoidInstances$$given_Monoid_Int$.html#combine-f47","e":false,"i":"","n":"combine","t":"combine(a: Int, b: Int): Int","d":"kuram.MonoidInstances.given_Monoid_Int","k":"def","x":""},
{"l":"kuram/MonoidInstances$$given_Monoid_Int$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: Int","d":"kuram.MonoidInstances.given_Monoid_Int","k":"def","x":""},
{"l":"kuram/MonoidInstances$$given_Monoid_String$.html#","e":false,"i":"","n":"given_Monoid_String","t":"given_Monoid_String extends Monoid[String]","d":"kuram.MonoidInstances","k":"object","x":""},
{"l":"kuram/MonoidInstances$$given_Monoid_String$.html#combine-fffff52f","e":false,"i":"","n":"combine","t":"combine(a: String, b: String): String","d":"kuram.MonoidInstances.given_Monoid_String","k":"def","x":""},
{"l":"kuram/MonoidInstances$$given_Monoid_String$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: String","d":"kuram.MonoidInstances.given_Monoid_String","k":"def","x":""},
{"l":"kuram/Semigroup.html#","e":false,"i":"","n":"Semigroup","t":"Semigroup[T]","d":"kuram","k":"trait","x":""},
{"l":"kuram/Semigroup.html#combine-fffffab9","e":false,"i":"","n":"combine","t":"combine(a: T, b: T): T","d":"kuram.Semigroup","k":"def","x":""},
{"l":"kuram/Semigroup$.html#","e":false,"i":"","n":"Semigroup","t":"Semigroup","d":"kuram","k":"object","x":""},
{"l":"kuram/Semigroup$.html#apply-f91","e":false,"i":"","n":"apply","t":"apply[T](using instance: Semigroup[T]): Semigroup[T]","d":"kuram.Semigroup","k":"def","x":""},
{"l":"kuram/SemigroupInstances$.html#","e":false,"i":"","n":"SemigroupInstances","t":"SemigroupInstances","d":"kuram","k":"object","x":""},
{"l":"kuram/SemigroupInstances$.html#given_Semigroup_Int-0","e":false,"i":"","n":"given_Semigroup_Int","t":"given_Semigroup_Int: given_Semigroup_Int","d":"kuram.SemigroupInstances","k":"given","x":""},
{"l":"kuram/SemigroupInstances$.html#given_Semigroup_List-fffff7d0","e":false,"i":"","n":"given_Semigroup_List","t":"given_Semigroup_List[A]: given_Semigroup_List[A]","d":"kuram.SemigroupInstances","k":"given","x":""},
{"l":"kuram/SemigroupInstances$.html#given_Semigroup_String-0","e":false,"i":"","n":"given_Semigroup_String","t":"given_Semigroup_String: given_Semigroup_String","d":"kuram.SemigroupInstances","k":"given","x":""},
{"l":"kuram/SemigroupInstances$$given_Semigroup_Int$.html#","e":false,"i":"","n":"given_Semigroup_Int","t":"given_Semigroup_Int extends Semigroup[Int]","d":"kuram.SemigroupInstances","k":"object","x":""},
{"l":"kuram/SemigroupInstances$$given_Semigroup_Int$.html#combine-f47","e":false,"i":"","n":"combine","t":"combine(a: Int, b: Int): Int","d":"kuram.SemigroupInstances.given_Semigroup_Int","k":"def","x":""},
{"l":"kuram/SemigroupInstances$$given_Semigroup_String$.html#","e":false,"i":"","n":"given_Semigroup_String","t":"given_Semigroup_String extends Semigroup[String]","d":"kuram.SemigroupInstances","k":"object","x":""},
{"l":"kuram/SemigroupInstances$$given_Semigroup_String$.html#combine-fffff52f","e":false,"i":"","n":"combine","t":"combine(a: String, b: String): String","d":"kuram.SemigroupInstances.given_Semigroup_String","k":"def","x":""},
{"l":"kuram/SemigroupSyntax$.html#","e":false,"i":"","n":"SemigroupSyntax","t":"SemigroupSyntax","d":"kuram","k":"object","x":""},
{"l":"kuram/SemigroupSyntax$.html#|+|-fffff013","e":false,"i":"extension [T](a: T)","n":"|+|","t":"|+|(b: T)(using semigroup: Semigroup[T]): T","d":"kuram.SemigroupSyntax","k":"def","x":""}];