pages = [{"l":"index.html#","e":false,"i":"","n":"kuram","t":"kuram","d":"","k":"static","x":""},
{"l":"kuram.html#","e":false,"i":"","n":"kuram","t":"kuram","d":"","k":"package","x":""},
{"l":"kuram.html#run-0","e":false,"i":"","n":"run","t":"run: Unit","d":"kuram","k":"def","x":""},
{"l":"kuram/applicative.html#","e":false,"i":"","n":"kuram.applicative","t":"kuram.applicative","d":"","k":"package","x":""},
{"l":"kuram/applicative/instances.html#","e":false,"i":"","n":"kuram.applicative.instances","t":"kuram.applicative.instances","d":"","k":"package","x":""},
{"l":"kuram/applicative/instances/all$.html#","e":false,"i":"","n":"all","t":"all","d":"kuram.applicative.instances","k":"object","x":""},
{"l":"kuram/applicative/instances/list$.html#","e":false,"i":"","n":"list","t":"list","d":"kuram.applicative.instances","k":"object","x":""},
{"l":"kuram/applicative/instances/list$.html#listApplicative-0","e":false,"i":"","n":"listApplicative","t":"listApplicative: listApplicative","d":"kuram.applicative.instances.list","k":"given","x":""},
{"l":"kuram/applicative/instances/list$$listApplicative$.html#","e":false,"i":"","n":"listApplicative","t":"listApplicative extends Applicative[List]","d":"kuram.applicative.instances.list","k":"object","x":""},
{"l":"kuram/applicative/instances/list$$listApplicative$.html#ap-fffff3a0","e":false,"i":"","n":"ap","t":"ap[A, B](ff: List[A => B])(fa: List[A]): List[B]","d":"kuram.applicative.instances.list.listApplicative","k":"def","x":""},
{"l":"kuram/applicative/instances/list$$listApplicative$.html#pure-833","e":false,"i":"","n":"pure","t":"pure[A](a: => A): List[A]","d":"kuram.applicative.instances.list.listApplicative","k":"def","x":""},
{"l":"kuram/applicative/instances/map$.html#","e":false,"i":"","n":"map","t":"map","d":"kuram.applicative.instances","k":"object","x":""},
{"l":"kuram/applicative/instances/map$.html#mapApplicative-623","e":false,"i":"","n":"mapApplicative","t":"mapApplicative[K]: mapApplicative[K]","d":"kuram.applicative.instances.map","k":"given","x":""},
{"l":"kuram/applicative/instances/option$.html#","e":false,"i":"","n":"option","t":"option","d":"kuram.applicative.instances","k":"object","x":""},
{"l":"kuram/applicative/instances/option$.html#optionApplicative-0","e":false,"i":"","n":"optionApplicative","t":"optionApplicative: optionApplicative","d":"kuram.applicative.instances.option","k":"given","x":""},
{"l":"kuram/applicative/instances/option$$optionApplicative$.html#","e":false,"i":"","n":"optionApplicative","t":"optionApplicative extends Applicative[Option]","d":"kuram.applicative.instances.option","k":"object","x":""},
{"l":"kuram/applicative/instances/option$$optionApplicative$.html#ap-fffff769","e":false,"i":"","n":"ap","t":"ap[A, B](ff: Option[A => B])(fa: Option[A]): Option[B]","d":"kuram.applicative.instances.option.optionApplicative","k":"def","x":""},
{"l":"kuram/applicative/instances/option$$optionApplicative$.html#pure-bfc","e":false,"i":"","n":"pure","t":"pure[A](a: => A): Option[A]","d":"kuram.applicative.instances.option.optionApplicative","k":"def","x":""},
{"l":"kuram/applicative/Applicative.html#","e":false,"i":"","n":"Applicative","t":"Applicative[F[_]] extends Apply[F]","d":"kuram.applicative","k":"trait","x":""},
{"l":"kuram/applicative/Applicative.html#map-fffffd97","e":false,"i":"extension [A](fa: F[A])","n":"map","t":"map[B](f: A => B): F[B]","d":"kuram.applicative.Applicative","k":"def","x":""},
{"l":"kuram/applicative/Applicative.html#pure-fffff7d2","e":false,"i":"","n":"pure","t":"pure[A](a: => A): F[A]","d":"kuram.applicative.Applicative","k":"def","x":""},
{"l":"kuram/applicative/Applicative$.html#","e":false,"i":"","n":"Applicative","t":"Applicative","d":"kuram.applicative","k":"object","x":""},
{"l":"kuram/applicative/Applicative$.html#apply-fffffbf1","e":false,"i":"","n":"apply","t":"apply[F[_]](using instance: Applicative[F]): Applicative[F]","d":"kuram.applicative.Applicative","k":"def","x":""},
{"l":"kuram/apply.html#","e":false,"i":"","n":"kuram.apply","t":"kuram.apply","d":"","k":"package","x":""},
{"l":"kuram/apply/instances.html#","e":false,"i":"","n":"kuram.apply.instances","t":"kuram.apply.instances","d":"","k":"package","x":""},
{"l":"kuram/apply/instances/all$.html#","e":false,"i":"","n":"all","t":"all","d":"kuram.apply.instances","k":"object","x":""},
{"l":"kuram/apply/instances/list$.html#","e":false,"i":"","n":"list","t":"list","d":"kuram.apply.instances","k":"object","x":""},
{"l":"kuram/apply/instances/list$.html#listApply-0","e":false,"i":"","n":"listApply","t":"listApply: listApply","d":"kuram.apply.instances.list","k":"given","x":""},
{"l":"kuram/apply/instances/list$$listApply$.html#","e":false,"i":"","n":"listApply","t":"listApply extends Apply[List]","d":"kuram.apply.instances.list","k":"object","x":""},
{"l":"kuram/apply/instances/list$$listApply$.html#ap-fffff3a0","e":false,"i":"","n":"ap","t":"ap[A, B](ff: List[A => B])(fa: List[A]): List[B]","d":"kuram.apply.instances.list.listApply","k":"def","x":""},
{"l":"kuram/apply/instances/list$$listApply$.html#map-fffff3f1","e":false,"i":"extension [A](fa: List[A])","n":"map","t":"map[B](f: A => B): List[B]","d":"kuram.apply.instances.list.listApply","k":"def","x":""},
{"l":"kuram/apply/instances/map$.html#","e":false,"i":"","n":"map","t":"map","d":"kuram.apply.instances","k":"object","x":""},
{"l":"kuram/apply/instances/map$.html#mapApply-fffff263","e":false,"i":"","n":"mapApply","t":"mapApply[K]: mapApply[K]","d":"kuram.apply.instances.map","k":"given","x":""},
{"l":"kuram/apply/instances/option$.html#","e":false,"i":"","n":"option","t":"option","d":"kuram.apply.instances","k":"object","x":""},
{"l":"kuram/apply/instances/option$.html#optionApply-0","e":false,"i":"","n":"optionApply","t":"optionApply: optionApply","d":"kuram.apply.instances.option","k":"given","x":""},
{"l":"kuram/apply/instances/option$$optionApply$.html#","e":false,"i":"","n":"optionApply","t":"optionApply extends Apply[Option]","d":"kuram.apply.instances.option","k":"object","x":""},
{"l":"kuram/apply/instances/option$$optionApply$.html#ap-fffff769","e":false,"i":"","n":"ap","t":"ap[A, B](ff: Option[A => B])(fa: Option[A]): Option[B]","d":"kuram.apply.instances.option.optionApply","k":"def","x":""},
{"l":"kuram/apply/instances/option$$optionApply$.html#map-fffff66b","e":false,"i":"extension [A](fa: Option[A])","n":"map","t":"map[B](f: A => B): Option[B]","d":"kuram.apply.instances.option.optionApply","k":"def","x":""},
{"l":"kuram/apply/Apply.html#","e":false,"i":"","n":"Apply","t":"Apply[F[_]] extends Functor[F]","d":"kuram.apply","k":"trait","x":""},
{"l":"kuram/apply/Apply.html#ap-fffffeeb","e":false,"i":"","n":"ap","t":"ap[A, B](ff: F[A => B])(fa: F[A]): F[B]","d":"kuram.apply.Apply","k":"def","x":""},
{"l":"kuram/apply/Apply$.html#","e":false,"i":"","n":"Apply","t":"Apply","d":"kuram.apply","k":"object","x":""},
{"l":"kuram/apply/Apply$.html#apply-fffff671","e":false,"i":"","n":"apply","t":"apply[F[_]](using instance: Apply[F]): Apply[F]","d":"kuram.apply.Apply","k":"def","x":""},
{"l":"kuram/category.html#","e":false,"i":"","n":"kuram.category","t":"kuram.category","d":"","k":"package","x":""},
{"l":"kuram/category/instances.html#","e":false,"i":"","n":"kuram.category.instances","t":"kuram.category.instances","d":"","k":"package","x":""},
{"l":"kuram/category/instances/all$.html#","e":false,"i":"","n":"all","t":"all","d":"kuram.category.instances","k":"object","x":""},
{"l":"kuram/category/instances/function1$.html#","e":false,"i":"","n":"function1","t":"function1","d":"kuram.category.instances","k":"object","x":""},
{"l":"kuram/category/instances/function1$.html#function1Category-0","e":false,"i":"","n":"function1Category","t":"function1Category: function1Category","d":"kuram.category.instances.function1","k":"given","x":""},
{"l":"kuram/category/instances/function1$$function1Category$.html#","e":false,"i":"","n":"function1Category","t":"function1Category extends Category[Function1]","d":"kuram.category.instances.function1","k":"object","x":""},
{"l":"kuram/category/instances/function1$$function1Category$.html#compose-35e","e":false,"i":"","n":"compose","t":"compose[A, B, C](f: B => C, g: A => B): A => C","d":"kuram.category.instances.function1.function1Category","k":"def","x":""},
{"l":"kuram/category/instances/function1$$function1Category$.html#id-c40","e":false,"i":"","n":"id","t":"id[A]: A => A","d":"kuram.category.instances.function1.function1Category","k":"def","x":""},
{"l":"kuram/category/Category.html#","e":false,"i":"","n":"Category","t":"Category[F[_, _]] extends Compose[F]","d":"kuram.category","k":"trait","x":""},
{"l":"kuram/category/Category.html#id-fffff7c4","e":false,"i":"","n":"id","t":"id[A]: F[A, A]","d":"kuram.category.Category","k":"def","x":""},
{"l":"kuram/category/Category$.html#","e":false,"i":"","n":"Category","t":"Category","d":"kuram.category","k":"object","x":""},
{"l":"kuram/category/Category$.html#apply-bf1","e":false,"i":"","n":"apply","t":"apply[F[_, _]](using instance: Category[F]): Category[F]","d":"kuram.category.Category","k":"def","x":""},
{"l":"kuram/compose.html#","e":false,"i":"","n":"kuram.compose","t":"kuram.compose","d":"","k":"package","x":""},
{"l":"kuram/compose/instances.html#","e":false,"i":"","n":"kuram.compose.instances","t":"kuram.compose.instances","d":"","k":"package","x":""},
{"l":"kuram/compose/instances/all$.html#","e":false,"i":"","n":"all","t":"all","d":"kuram.compose.instances","k":"object","x":""},
{"l":"kuram/compose/instances/function1$.html#","e":false,"i":"","n":"function1","t":"function1","d":"kuram.compose.instances","k":"object","x":""},
{"l":"kuram/compose/instances/function1$.html#function1Compose-0","e":false,"i":"","n":"function1Compose","t":"function1Compose: function1Compose","d":"kuram.compose.instances.function1","k":"given","x":""},
{"l":"kuram/compose/instances/function1$$function1Compose$.html#","e":false,"i":"","n":"function1Compose","t":"function1Compose extends Compose[Function1]","d":"kuram.compose.instances.function1","k":"object","x":""},
{"l":"kuram/compose/instances/function1$$function1Compose$.html#compose-35e","e":false,"i":"","n":"compose","t":"compose[A, B, C](f: B => C, g: A => B): A => C","d":"kuram.compose.instances.function1.function1Compose","k":"def","x":""},
{"l":"kuram/compose/syntax.html#","e":false,"i":"","n":"kuram.compose.syntax","t":"kuram.compose.syntax","d":"","k":"package","x":""},
{"l":"kuram/compose/syntax.html#<<<-fffffe15","e":false,"i":"extension [F[_, _], A, B, C](f: F[B, C])","n":"<<<","t":"<<<(g: F[A, B])(using c: Compose[F]): F[A, C]","d":"kuram.compose.syntax","k":"def","x":""},
{"l":"kuram/compose/syntax.html#>>>-fffffe15","e":false,"i":"extension [F[_, _], A, B, C](f: F[A, B])","n":">>>","t":">>>(g: F[B, C])(using c: Compose[F]): F[A, C]","d":"kuram.compose.syntax","k":"def","x":""},
{"l":"kuram/compose/Compose.html#","e":false,"i":"","n":"Compose","t":"Compose[F[_, _]]","d":"kuram.compose","k":"trait","x":""},
{"l":"kuram/compose/Compose.html#andThen-fffff8ec","e":false,"i":"","n":"andThen","t":"andThen[A, B, C](f: F[A, B], g: F[B, C]): F[A, C]","d":"kuram.compose.Compose","k":"def","x":""},
{"l":"kuram/compose/Compose.html#compose-fffff8ec","e":false,"i":"","n":"compose","t":"compose[A, B, C](f: F[B, C], g: F[A, B]): F[A, C]","d":"kuram.compose.Compose","k":"def","x":""},
{"l":"kuram/compose/Compose$.html#","e":false,"i":"","n":"Compose","t":"Compose","d":"kuram.compose","k":"object","x":""},
{"l":"kuram/compose/Compose$.html#apply-fffffc71","e":false,"i":"","n":"apply","t":"apply[F[_, _]](using instance: Compose[F]): Compose[F]","d":"kuram.compose.Compose","k":"def","x":""},
{"l":"kuram/foldable.html#","e":false,"i":"","n":"kuram.foldable","t":"kuram.foldable","d":"","k":"package","x":""},
{"l":"kuram/foldable/instances.html#","e":false,"i":"","n":"kuram.foldable.instances","t":"kuram.foldable.instances","d":"","k":"package","x":""},
{"l":"kuram/foldable/instances/all$.html#","e":false,"i":"","n":"all","t":"all","d":"kuram.foldable.instances","k":"object","x":""},
{"l":"kuram/foldable/instances/indexedSeq$.html#","e":false,"i":"","n":"indexedSeq","t":"indexedSeq","d":"kuram.foldable.instances","k":"object","x":""},
{"l":"kuram/foldable/instances/indexedSeq$.html#indexedSeqFoldable-0","e":false,"i":"","n":"indexedSeqFoldable","t":"indexedSeqFoldable: indexedSeqFoldable","d":"kuram.foldable.instances.indexedSeq","k":"given","x":""},
{"l":"kuram/foldable/instances/indexedSeq$$indexedSeqFoldable$.html#","e":false,"i":"","n":"indexedSeqFoldable","t":"indexedSeqFoldable extends Foldable[IndexedSeq]","d":"kuram.foldable.instances.indexedSeq","k":"object","x":""},
{"l":"kuram/foldable/instances/list$.html#","e":false,"i":"","n":"list","t":"list","d":"kuram.foldable.instances","k":"object","x":""},
{"l":"kuram/foldable/instances/list$.html#listFoldable-0","e":false,"i":"","n":"listFoldable","t":"listFoldable: listFoldable","d":"kuram.foldable.instances.list","k":"given","x":""},
{"l":"kuram/foldable/instances/list$$listFoldable$.html#","e":false,"i":"","n":"listFoldable","t":"listFoldable extends Foldable[List]","d":"kuram.foldable.instances.list","k":"object","x":""},
{"l":"kuram/foldable/syntax.html#","e":false,"i":"","n":"kuram.foldable.syntax","t":"kuram.foldable.syntax","d":"","k":"package","x":""},
{"l":"kuram/foldable/syntax.html#@<<-fffff50e","e":false,"i":"extension [F[_], A, B](foldable: F[A])(implicit evidence$1: Foldable[F])","n":"@<<","t":"@<<: B","d":"kuram.foldable.syntax","k":"def","x":""},
{"l":"kuram/foldable/syntax.html#@>>-fffff50e","e":false,"i":"extension [F[_], A, B](foldable: F[A])(implicit evidence$1: Foldable[F])","n":"@>>","t":"@>>: B","d":"kuram.foldable.syntax","k":"def","x":""},
{"l":"kuram/foldable/Foldable.html#","e":false,"i":"","n":"Foldable","t":"Foldable[F[_]]","d":"kuram.foldable","k":"trait","x":""},
{"l":"kuram/foldable/Foldable.html#foldLeft-fffff9a5","e":false,"i":"extension [A](as: F[A])","n":"foldLeft","t":"foldLeft[B](acc: B)(f: (B, A) => B): B","d":"kuram.foldable.Foldable","k":"def","x":""},
{"l":"kuram/foldable/Foldable.html#foldMap-fffff123","e":false,"i":"extension [A](as: F[A])","n":"foldMap","t":"foldMap[B](f: A => B)(using m: Monoid[B]): B","d":"kuram.foldable.Foldable","k":"def","x":""},
{"l":"kuram/foldable/Foldable.html#foldRight-fffff9a5","e":false,"i":"extension [A](as: F[A])","n":"foldRight","t":"foldRight[B](acc: B)(f: (A, B) => B): B","d":"kuram.foldable.Foldable","k":"def","x":""},
{"l":"kuram/foldable/Foldable$.html#","e":false,"i":"","n":"Foldable","t":"Foldable","d":"kuram.foldable","k":"object","x":""},
{"l":"kuram/foldable/Foldable$.html#apply-fffff7f1","e":false,"i":"","n":"apply","t":"apply[F[_]](using instance: Foldable[F]): Foldable[F]","d":"kuram.foldable.Foldable","k":"def","x":""},
{"l":"kuram/functor.html#","e":false,"i":"","n":"kuram.functor","t":"kuram.functor","d":"","k":"package","x":""},
{"l":"kuram/functor/instances.html#","e":false,"i":"","n":"kuram.functor.instances","t":"kuram.functor.instances","d":"","k":"package","x":""},
{"l":"kuram/functor/instances/all$.html#","e":false,"i":"","n":"all","t":"all","d":"kuram.functor.instances","k":"object","x":""},
{"l":"kuram/functor/instances/list$.html#","e":false,"i":"","n":"list","t":"list","d":"kuram.functor.instances","k":"object","x":""},
{"l":"kuram/functor/instances/list$.html#listFunctor-0","e":false,"i":"","n":"listFunctor","t":"listFunctor: listFunctor","d":"kuram.functor.instances.list","k":"given","x":""},
{"l":"kuram/functor/instances/list$$listFunctor$.html#","e":false,"i":"","n":"listFunctor","t":"listFunctor extends Functor[List]","d":"kuram.functor.instances.list","k":"object","x":""},
{"l":"kuram/functor/instances/list$$listFunctor$.html#map-fffff3f1","e":false,"i":"extension [A](as: List[A])","n":"map","t":"map[B](f: A => B): List[B]","d":"kuram.functor.instances.list.listFunctor","k":"def","x":""},
{"l":"kuram/functor/instances/map$.html#","e":false,"i":"","n":"map","t":"map","d":"kuram.functor.instances","k":"object","x":""},
{"l":"kuram/functor/instances/map$.html#mapFunctor-43","e":false,"i":"","n":"mapFunctor","t":"mapFunctor[K]: mapFunctor[K]","d":"kuram.functor.instances.map","k":"given","x":""},
{"l":"kuram/functor/instances/option$.html#","e":false,"i":"","n":"option","t":"option","d":"kuram.functor.instances","k":"object","x":""},
{"l":"kuram/functor/instances/option$.html#optionFunctor-0","e":false,"i":"","n":"optionFunctor","t":"optionFunctor: optionFunctor","d":"kuram.functor.instances.option","k":"given","x":""},
{"l":"kuram/functor/instances/option$$optionFunctor$.html#","e":false,"i":"","n":"optionFunctor","t":"optionFunctor extends Functor[Option]","d":"kuram.functor.instances.option","k":"object","x":""},
{"l":"kuram/functor/instances/option$$optionFunctor$.html#map-fffff66b","e":false,"i":"extension [A](fa: Option[A])","n":"map","t":"map[B](f: A => B): Option[B]","d":"kuram.functor.instances.option.optionFunctor","k":"def","x":""},
{"l":"kuram/functor/syntax.html#","e":false,"i":"","n":"kuram.functor.syntax","t":"kuram.functor.syntax","d":"","k":"package","x":""},
{"l":"kuram/functor/syntax.html#|>-206","e":false,"i":"extension [F[_], A, B](functor: F[A])(implicit evidence$1: Functor[F])","n":"|>","t":"|>: F[B]","d":"kuram.functor.syntax","k":"def","x":""},
{"l":"kuram/functor/Functor.html#","e":false,"i":"","n":"Functor","t":"Functor[F[_]]","d":"kuram.functor","k":"trait","x":""},
{"l":"kuram/functor/Functor.html#fmap-fffffd97","e":false,"i":"extension [A](fa: F[A])","n":"fmap","t":"fmap[B](f: A => B): F[B]","d":"kuram.functor.Functor","k":"def","x":""},
{"l":"kuram/functor/Functor.html#map-fffffd97","e":false,"i":"extension [A](fa: F[A])","n":"map","t":"map[B](f: A => B): F[B]","d":"kuram.functor.Functor","k":"def","x":""},
{"l":"kuram/functor/Functor$.html#","e":false,"i":"","n":"Functor","t":"Functor","d":"kuram.functor","k":"object","x":""},
{"l":"kuram/functor/Functor$.html#apply-1b1","e":false,"i":"","n":"apply","t":"apply[F[_]](using instance: Functor[F]): Functor[F]","d":"kuram.functor.Functor","k":"def","x":""},
{"l":"kuram/kuram.html#","e":false,"i":"","n":"kuram.kuram","t":"kuram.kuram","d":"","k":"package","x":""},
{"l":"kuram/monad.html#","e":false,"i":"","n":"kuram.monad","t":"kuram.monad","d":"","k":"package","x":""},
{"l":"kuram/monad/instances.html#","e":false,"i":"","n":"kuram.monad.instances","t":"kuram.monad.instances","d":"","k":"package","x":""},
{"l":"kuram/monad/instances/all$.html#","e":false,"i":"","n":"all","t":"all","d":"kuram.monad.instances","k":"object","x":""},
{"l":"kuram/monad/instances/list$.html#","e":false,"i":"","n":"list","t":"list","d":"kuram.monad.instances","k":"object","x":""},
{"l":"kuram/monad/instances/list$.html#listMonad-0","e":false,"i":"","n":"listMonad","t":"listMonad: listMonad","d":"kuram.monad.instances.list","k":"given","x":""},
{"l":"kuram/monad/instances/list$$listMonad$.html#","e":false,"i":"","n":"listMonad","t":"listMonad extends Monad[List]","d":"kuram.monad.instances.list","k":"object","x":""},
{"l":"kuram/monad/instances/list$$listMonad$.html#ap-fffff3a0","e":false,"i":"","n":"ap","t":"ap[A, B](ff: List[A => B])(fa: List[A]): List[B]","d":"kuram.monad.instances.list.listMonad","k":"def","x":""},
{"l":"kuram/monad/instances/list$$listMonad$.html#flatMap-fffff3f1","e":false,"i":"extension [A](fa: List[A])","n":"flatMap","t":"flatMap[B](f: A => List[B]): List[B]","d":"kuram.monad.instances.list.listMonad","k":"def","x":""},
{"l":"kuram/monad/instances/list$$listMonad$.html#pure-833","e":false,"i":"","n":"pure","t":"pure[A](a: => A): List[A]","d":"kuram.monad.instances.list.listMonad","k":"def","x":""},
{"l":"kuram/monad/instances/map$.html#","e":false,"i":"","n":"map","t":"map","d":"kuram.monad.instances","k":"object","x":""},
{"l":"kuram/monad/instances/map$.html#mapMonad-e83","e":false,"i":"","n":"mapMonad","t":"mapMonad[K]: mapMonad[K]","d":"kuram.monad.instances.map","k":"given","x":""},
{"l":"kuram/monad/instances/option$.html#","e":false,"i":"","n":"option","t":"option","d":"kuram.monad.instances","k":"object","x":""},
{"l":"kuram/monad/instances/option$.html#optionMonad-0","e":false,"i":"","n":"optionMonad","t":"optionMonad: optionMonad","d":"kuram.monad.instances.option","k":"given","x":""},
{"l":"kuram/monad/instances/option$$optionMonad$.html#","e":false,"i":"","n":"optionMonad","t":"optionMonad extends Monad[Option]","d":"kuram.monad.instances.option","k":"object","x":""},
{"l":"kuram/monad/instances/option$$optionMonad$.html#ap-fffff769","e":false,"i":"","n":"ap","t":"ap[A, B](ff: Option[A => B])(fa: Option[A]): Option[B]","d":"kuram.monad.instances.option.optionMonad","k":"def","x":""},
{"l":"kuram/monad/instances/option$$optionMonad$.html#flatMap-fffff66b","e":false,"i":"extension [A](fa: Option[A])","n":"flatMap","t":"flatMap[B](f: A => Option[B]): Option[B]","d":"kuram.monad.instances.option.optionMonad","k":"def","x":""},
{"l":"kuram/monad/instances/option$$optionMonad$.html#pure-bfc","e":false,"i":"","n":"pure","t":"pure[A](a: => A): Option[A]","d":"kuram.monad.instances.option.optionMonad","k":"def","x":""},
{"l":"kuram/monad/Monad.html#","e":false,"i":"","n":"Monad","t":"Monad[F[_]] extends Applicative[F]","d":"kuram.monad","k":"trait","x":""},
{"l":"kuram/monad/Monad.html#flatMap-fffffd97","e":false,"i":"extension [A](fa: F[A])","n":"flatMap","t":"flatMap[B](f: A => F[B]): F[B]","d":"kuram.monad.Monad","k":"def","x":""},
{"l":"kuram/monad/Monad$.html#","e":false,"i":"","n":"Monad","t":"Monad","d":"kuram.monad","k":"object","x":""},
{"l":"kuram/monad/Monad$.html#apply-fffff2b1","e":false,"i":"","n":"apply","t":"apply[F[_]](using instance: Monad[F]): Monad[F]","d":"kuram.monad.Monad","k":"def","x":""},
{"l":"kuram/monoid.html#","e":false,"i":"","n":"kuram.monoid","t":"kuram.monoid","d":"","k":"package","x":""},
{"l":"kuram/monoid/instances.html#","e":false,"i":"","n":"kuram.monoid.instances","t":"kuram.monoid.instances","d":"","k":"package","x":""},
{"l":"kuram/monoid/instances/all$.html#","e":false,"i":"","n":"all","t":"all","d":"kuram.monoid.instances","k":"object","x":""},
{"l":"kuram/monoid/instances/boolean$.html#","e":false,"i":"","n":"boolean","t":"boolean","d":"kuram.monoid.instances","k":"object","x":""},
{"l":"kuram/monoid/instances/boolean$.html#conjuctionBooleanMonoid-0","e":false,"i":"","n":"conjuctionBooleanMonoid","t":"conjuctionBooleanMonoid: conjuctionBooleanMonoid","d":"kuram.monoid.instances.boolean","k":"given","x":""},
{"l":"kuram/monoid/instances/boolean$.html#disjunctionBooleanMonoid-0","e":false,"i":"","n":"disjunctionBooleanMonoid","t":"disjunctionBooleanMonoid: disjunctionBooleanMonoid","d":"kuram.monoid.instances.boolean","k":"given","x":""},
{"l":"kuram/monoid/instances/boolean$$conjuctionBooleanMonoid$.html#","e":false,"i":"","n":"conjuctionBooleanMonoid","t":"conjuctionBooleanMonoid extends Monoid[Boolean]","d":"kuram.monoid.instances.boolean","k":"object","x":""},
{"l":"kuram/monoid/instances/boolean$$conjuctionBooleanMonoid$.html#combine-b60","e":false,"i":"","n":"combine","t":"combine(a: Boolean, b: Boolean): Boolean","d":"kuram.monoid.instances.boolean.conjuctionBooleanMonoid","k":"def","x":""},
{"l":"kuram/monoid/instances/boolean$$conjuctionBooleanMonoid$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: Boolean","d":"kuram.monoid.instances.boolean.conjuctionBooleanMonoid","k":"def","x":""},
{"l":"kuram/monoid/instances/boolean$$disjunctionBooleanMonoid$.html#","e":false,"i":"","n":"disjunctionBooleanMonoid","t":"disjunctionBooleanMonoid extends Monoid[Boolean]","d":"kuram.monoid.instances.boolean","k":"object","x":""},
{"l":"kuram/monoid/instances/boolean$$disjunctionBooleanMonoid$.html#combine-b60","e":false,"i":"","n":"combine","t":"combine(a: Boolean, b: Boolean): Boolean","d":"kuram.monoid.instances.boolean.disjunctionBooleanMonoid","k":"def","x":""},
{"l":"kuram/monoid/instances/boolean$$disjunctionBooleanMonoid$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: Boolean","d":"kuram.monoid.instances.boolean.disjunctionBooleanMonoid","k":"def","x":""},
{"l":"kuram/monoid/instances/int$.html#","e":false,"i":"","n":"int","t":"int","d":"kuram.monoid.instances","k":"object","x":""},
{"l":"kuram/monoid/instances/int$.html#intMonoid-0","e":false,"i":"","n":"intMonoid","t":"intMonoid: intMonoid","d":"kuram.monoid.instances.int","k":"given","x":""},
{"l":"kuram/monoid/instances/int$$intMonoid$.html#","e":false,"i":"","n":"intMonoid","t":"intMonoid extends Monoid[Int]","d":"kuram.monoid.instances.int","k":"object","x":""},
{"l":"kuram/monoid/instances/int$$intMonoid$.html#combine-f47","e":false,"i":"","n":"combine","t":"combine(a: Int, b: Int): Int","d":"kuram.monoid.instances.int.intMonoid","k":"def","x":""},
{"l":"kuram/monoid/instances/int$$intMonoid$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: Int","d":"kuram.monoid.instances.int.intMonoid","k":"def","x":""},
{"l":"kuram/monoid/instances/list$.html#","e":false,"i":"","n":"list","t":"list","d":"kuram.monoid.instances","k":"object","x":""},
{"l":"kuram/monoid/instances/list$.html#listMonoid-43f","e":false,"i":"","n":"listMonoid","t":"listMonoid[A]: listMonoid[A]","d":"kuram.monoid.instances.list","k":"given","x":""},
{"l":"kuram/monoid/instances/map$.html#","e":false,"i":"","n":"map","t":"map","d":"kuram.monoid.instances","k":"object","x":""},
{"l":"kuram/monoid/instances/map$.html#mapMonoid-fffff420","e":false,"i":"","n":"mapMonoid","t":"mapMonoid[K, V : Monoid]: mapMonoid[K, V]","d":"kuram.monoid.instances.map","k":"given","x":""},
{"l":"kuram/monoid/instances/option$.html#","e":false,"i":"","n":"option","t":"option","d":"kuram.monoid.instances","k":"object","x":""},
{"l":"kuram/monoid/instances/option$.html#optionMonoid-ffffffff","e":false,"i":"","n":"optionMonoid","t":"optionMonoid[A : Monoid]: optionMonoid[A]","d":"kuram.monoid.instances.option","k":"given","x":""},
{"l":"kuram/monoid/instances/set$.html#","e":false,"i":"","n":"set","t":"set","d":"kuram.monoid.instances","k":"object","x":""},
{"l":"kuram/monoid/instances/set$.html#intersectSetMonoid-1d2","e":false,"i":"","n":"intersectSetMonoid","t":"intersectSetMonoid[A]: intersectSetMonoid[A]","d":"kuram.monoid.instances.set","k":"given","x":""},
{"l":"kuram/monoid/instances/set$.html#unionSetMonoid-fffff6a2","e":false,"i":"","n":"unionSetMonoid","t":"unionSetMonoid[A]: unionSetMonoid[A]","d":"kuram.monoid.instances.set","k":"given","x":""},
{"l":"kuram/monoid/instances/string$.html#","e":false,"i":"","n":"string","t":"string","d":"kuram.monoid.instances","k":"object","x":""},
{"l":"kuram/monoid/instances/string$.html#stringMonoid-0","e":false,"i":"","n":"stringMonoid","t":"stringMonoid: stringMonoid","d":"kuram.monoid.instances.string","k":"given","x":""},
{"l":"kuram/monoid/instances/string$$stringMonoid$.html#","e":false,"i":"","n":"stringMonoid","t":"stringMonoid extends Monoid[String]","d":"kuram.monoid.instances.string","k":"object","x":""},
{"l":"kuram/monoid/instances/string$$stringMonoid$.html#combine-fffff52f","e":false,"i":"","n":"combine","t":"combine(a: String, b: String): String","d":"kuram.monoid.instances.string.stringMonoid","k":"def","x":""},
{"l":"kuram/monoid/instances/string$$stringMonoid$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: String","d":"kuram.monoid.instances.string.stringMonoid","k":"def","x":""},
{"l":"kuram/monoid/Monoid.html#","e":false,"i":"","n":"Monoid","t":"Monoid[T] extends Semigroup[T]","d":"kuram.monoid","k":"trait","x":""},
{"l":"kuram/monoid/Monoid.html#empty-0","e":false,"i":"","n":"empty","t":"empty: T","d":"kuram.monoid.Monoid","k":"def","x":""},
{"l":"kuram/monoid/Monoid$.html#","e":false,"i":"","n":"Monoid","t":"Monoid","d":"kuram.monoid","k":"object","x":""},
{"l":"kuram/monoid/Monoid$.html#apply-2f1","e":false,"i":"","n":"apply","t":"apply[T](using instance: Monoid[T]): Monoid[T]","d":"kuram.monoid.Monoid","k":"def","x":""},
{"l":"kuram/semigroup.html#","e":false,"i":"","n":"kuram.semigroup","t":"kuram.semigroup","d":"","k":"package","x":""},
{"l":"kuram/semigroup/instances.html#","e":false,"i":"","n":"kuram.semigroup.instances","t":"kuram.semigroup.instances","d":"","k":"package","x":""},
{"l":"kuram/semigroup/instances/all$.html#","e":false,"i":"","n":"all","t":"all","d":"kuram.semigroup.instances","k":"object","x":""},
{"l":"kuram/semigroup/instances/int$.html#","e":false,"i":"","n":"int","t":"int","d":"kuram.semigroup.instances","k":"object","x":""},
{"l":"kuram/semigroup/instances/int$.html#intSemigroup-0","e":false,"i":"","n":"intSemigroup","t":"intSemigroup: intSemigroup","d":"kuram.semigroup.instances.int","k":"given","x":""},
{"l":"kuram/semigroup/instances/int$$intSemigroup$.html#","e":false,"i":"","n":"intSemigroup","t":"intSemigroup extends Semigroup[Int]","d":"kuram.semigroup.instances.int","k":"object","x":""},
{"l":"kuram/semigroup/instances/int$$intSemigroup$.html#combine-f47","e":false,"i":"","n":"combine","t":"combine(a: Int, b: Int): Int","d":"kuram.semigroup.instances.int.intSemigroup","k":"def","x":""},
{"l":"kuram/semigroup/instances/list$.html#","e":false,"i":"","n":"list","t":"list","d":"kuram.semigroup.instances","k":"object","x":""},
{"l":"kuram/semigroup/instances/list$.html#listSemigroup-fffff2b3","e":false,"i":"","n":"listSemigroup","t":"listSemigroup[A]: listSemigroup[A]","d":"kuram.semigroup.instances.list","k":"given","x":""},
{"l":"kuram/semigroup/instances/string$.html#","e":false,"i":"","n":"string","t":"string","d":"kuram.semigroup.instances","k":"object","x":""},
{"l":"kuram/semigroup/instances/string$.html#stringSemigroup-0","e":false,"i":"","n":"stringSemigroup","t":"stringSemigroup: stringSemigroup","d":"kuram.semigroup.instances.string","k":"given","x":""},
{"l":"kuram/semigroup/instances/string$$stringSemigroup$.html#","e":false,"i":"","n":"stringSemigroup","t":"stringSemigroup extends Semigroup[String]","d":"kuram.semigroup.instances.string","k":"object","x":""},
{"l":"kuram/semigroup/instances/string$$stringSemigroup$.html#combine-fffff52f","e":false,"i":"","n":"combine","t":"combine(a: String, b: String): String","d":"kuram.semigroup.instances.string.stringSemigroup","k":"def","x":""},
{"l":"kuram/semigroup/syntax.html#","e":false,"i":"","n":"kuram.semigroup.syntax","t":"kuram.semigroup.syntax","d":"","k":"package","x":""},
{"l":"kuram/semigroup/syntax.html#|+|-fffff176","e":false,"i":"extension [T](a: T)","n":"|+|","t":"|+|(b: T)(using semigroup: Semigroup[T]): T","d":"kuram.semigroup.syntax","k":"def","x":""},
{"l":"kuram/semigroup/Semigroup.html#","e":false,"i":"","n":"Semigroup","t":"Semigroup[T]","d":"kuram.semigroup","k":"trait","x":""},
{"l":"kuram/semigroup/Semigroup.html#combine-fffffab9","e":false,"i":"","n":"combine","t":"combine(a: T, b: T): T","d":"kuram.semigroup.Semigroup","k":"def","x":""},
{"l":"kuram/semigroup/Semigroup$.html#","e":false,"i":"","n":"Semigroup","t":"Semigroup","d":"kuram.semigroup","k":"object","x":""},
{"l":"kuram/semigroup/Semigroup$.html#apply-fffffb31","e":false,"i":"","n":"apply","t":"apply[T](using instance: Semigroup[T]): Semigroup[T]","d":"kuram.semigroup.Semigroup","k":"def","x":""},
{"l":"kuram/run.html#","e":false,"i":"","n":"run","t":"run","d":"kuram","k":"class","x":""}];