pages = [{"l":"index.html#","e":false,"i":"","n":"kuram","t":"kuram","d":"","k":"static","x":""},
{"l":"kuram.html#","e":false,"i":"","n":"kuram","t":"kuram","d":"","k":"package","x":""},
{"l":"kuram/category.html#","e":false,"i":"","n":"kuram.category","t":"kuram.category","d":"","k":"package","x":""},
{"l":"kuram/category/instances.html#","e":false,"i":"","n":"kuram.category.instances","t":"kuram.category.instances","d":"","k":"package","x":""},
{"l":"kuram/category/Category.html#","e":false,"i":"","n":"Category","t":"Category[F[_, _]] extends Compose[F]","d":"kuram.category","k":"trait","x":""},
{"l":"kuram/category/Category.html#id-fffff7c4","e":false,"i":"","n":"id","t":"id[A]: F[A, A]","d":"kuram.category.Category","k":"def","x":""},
{"l":"kuram/category/Category$.html#","e":false,"i":"","n":"Category","t":"Category","d":"kuram.category","k":"object","x":""},
{"l":"kuram/category/Category$.html#apply-bf1","e":false,"i":"","n":"apply","t":"apply[F[_, _]](using instance: Category[F]): Category[F]","d":"kuram.category.Category","k":"def","x":""},
{"l":"kuram/category/CategoryInstances$.html#","e":false,"i":"","n":"CategoryInstances","t":"CategoryInstances","d":"kuram.category","k":"object","x":""},
{"l":"kuram/category/CategoryInstances$.html#given_Category_Function1-0","e":false,"i":"","n":"given_Category_Function1","t":"given_Category_Function1: given_Category_Function1","d":"kuram.category.CategoryInstances","k":"given","x":""},
{"l":"kuram/category/CategoryInstances$$given_Category_Function1$.html#","e":false,"i":"","n":"given_Category_Function1","t":"given_Category_Function1 extends Category[Function1]","d":"kuram.category.CategoryInstances","k":"object","x":""},
{"l":"kuram/category/CategoryInstances$$given_Category_Function1$.html#compose-35e","e":false,"i":"","n":"compose","t":"compose[A, B, C](f: B => C, g: A => B): A => C","d":"kuram.category.CategoryInstances.given_Category_Function1","k":"def","x":""},
{"l":"kuram/category/CategoryInstances$$given_Category_Function1$.html#id-c40","e":false,"i":"","n":"id","t":"id[A]: A => A","d":"kuram.category.CategoryInstances.given_Category_Function1","k":"def","x":""},
{"l":"kuram/compose.html#","e":false,"i":"","n":"kuram.compose","t":"kuram.compose","d":"","k":"package","x":""},
{"l":"kuram/compose/instances.html#","e":false,"i":"","n":"kuram.compose.instances","t":"kuram.compose.instances","d":"","k":"package","x":""},
{"l":"kuram/compose/Compose.html#","e":false,"i":"","n":"Compose","t":"Compose[F[_, _]]","d":"kuram.compose","k":"trait","x":""},
{"l":"kuram/compose/Compose.html#andThen-fffff8ec","e":false,"i":"","n":"andThen","t":"andThen[A, B, C](f: F[A, B], g: F[B, C]): F[A, C]","d":"kuram.compose.Compose","k":"def","x":""},
{"l":"kuram/compose/Compose.html#compose-fffff8ec","e":false,"i":"","n":"compose","t":"compose[A, B, C](f: F[B, C], g: F[A, B]): F[A, C]","d":"kuram.compose.Compose","k":"def","x":""},
{"l":"kuram/compose/Compose$.html#","e":false,"i":"","n":"Compose","t":"Compose","d":"kuram.compose","k":"object","x":""},
{"l":"kuram/compose/Compose$.html#apply-fffffc71","e":false,"i":"","n":"apply","t":"apply[F[_, _]](using instance: Compose[F]): Compose[F]","d":"kuram.compose.Compose","k":"def","x":""},
{"l":"kuram/compose/ComposeInstances$.html#","e":false,"i":"","n":"ComposeInstances","t":"ComposeInstances","d":"kuram.compose","k":"object","x":""},
{"l":"kuram/compose/ComposeInstances$.html#given_Compose_Function1-0","e":false,"i":"","n":"given_Compose_Function1","t":"given_Compose_Function1: given_Compose_Function1","d":"kuram.compose.ComposeInstances","k":"given","x":""},
{"l":"kuram/compose/ComposeInstances$$given_Compose_Function1$.html#","e":false,"i":"","n":"given_Compose_Function1","t":"given_Compose_Function1 extends Compose[Function1]","d":"kuram.compose.ComposeInstances","k":"object","x":""},
{"l":"kuram/compose/ComposeInstances$$given_Compose_Function1$.html#compose-35e","e":false,"i":"","n":"compose","t":"compose[A, B, C](f: B => C, g: A => B): A => C","d":"kuram.compose.ComposeInstances.given_Compose_Function1","k":"def","x":""},
{"l":"kuram/compose/ComposeSyntax$.html#","e":false,"i":"","n":"ComposeSyntax","t":"ComposeSyntax","d":"kuram.compose","k":"object","x":""},
{"l":"kuram/compose/ComposeSyntax$.html#<<<-fffffe15","e":false,"i":"extension [F[_, _], A, B, C](f: F[B, C])","n":"<<<","t":"<<<(g: F[A, B])(using c: Compose[F]): F[A, C]","d":"kuram.compose.ComposeSyntax","k":"def","x":""},
{"l":"kuram/compose/ComposeSyntax$.html#>>>-fffffe15","e":false,"i":"extension [F[_, _], A, B, C](f: F[A, B])","n":">>>","t":">>>(g: F[B, C])(using c: Compose[F]): F[A, C]","d":"kuram.compose.ComposeSyntax","k":"def","x":""},
{"l":"kuram/foldable.html#","e":false,"i":"","n":"kuram.foldable","t":"kuram.foldable","d":"","k":"package","x":""},
{"l":"kuram/foldable/instances.html#","e":false,"i":"","n":"kuram.foldable.instances","t":"kuram.foldable.instances","d":"","k":"package","x":""},
{"l":"kuram/foldable/Foldable.html#","e":false,"i":"","n":"Foldable","t":"Foldable[F[_]]","d":"kuram.foldable","k":"trait","x":""},
{"l":"kuram/foldable/Foldable.html#foldLeft-fffff9a5","e":false,"i":"extension [A](as: F[A])","n":"foldLeft","t":"foldLeft[B](acc: B)(f: (B, A) => B): B","d":"kuram.foldable.Foldable","k":"def","x":""},
{"l":"kuram/foldable/Foldable.html#foldMap-fffff123","e":false,"i":"extension [A](as: F[A])","n":"foldMap","t":"foldMap[B](f: A => B)(using m: Monoid[B]): B","d":"kuram.foldable.Foldable","k":"def","x":""},
{"l":"kuram/foldable/Foldable.html#foldRight-fffff9a5","e":false,"i":"extension [A](as: F[A])","n":"foldRight","t":"foldRight[B](acc: B)(f: (A, B) => B): B","d":"kuram.foldable.Foldable","k":"def","x":""},
{"l":"kuram/foldable/Foldable$.html#","e":false,"i":"","n":"Foldable","t":"Foldable","d":"kuram.foldable","k":"object","x":""},
{"l":"kuram/foldable/Foldable$.html#apply-fffff7f1","e":false,"i":"","n":"apply","t":"apply[F[_]](using instance: Foldable[F]): Foldable[F]","d":"kuram.foldable.Foldable","k":"def","x":""},
{"l":"kuram/foldable/FoldableInstances$.html#","e":false,"i":"","n":"FoldableInstances","t":"FoldableInstances","d":"kuram.foldable","k":"object","x":""},
{"l":"kuram/foldable/FoldableInstances$.html#given_Foldable_IndexedSeq-0","e":false,"i":"","n":"given_Foldable_IndexedSeq","t":"given_Foldable_IndexedSeq: given_Foldable_IndexedSeq","d":"kuram.foldable.FoldableInstances","k":"given","x":""},
{"l":"kuram/foldable/FoldableInstances$.html#given_Foldable_List-0","e":false,"i":"","n":"given_Foldable_List","t":"given_Foldable_List: given_Foldable_List","d":"kuram.foldable.FoldableInstances","k":"given","x":""},
{"l":"kuram/foldable/FoldableInstances$$given_Foldable_IndexedSeq$.html#","e":false,"i":"","n":"given_Foldable_IndexedSeq","t":"given_Foldable_IndexedSeq extends Foldable[IndexedSeq]","d":"kuram.foldable.FoldableInstances","k":"object","x":""},
{"l":"kuram/foldable/FoldableInstances$$given_Foldable_List$.html#","e":false,"i":"","n":"given_Foldable_List","t":"given_Foldable_List extends Foldable[List]","d":"kuram.foldable.FoldableInstances","k":"object","x":""},
{"l":"kuram/foldable/FoldableSyntax$.html#","e":false,"i":"","n":"FoldableSyntax","t":"FoldableSyntax","d":"kuram.foldable","k":"object","x":""},
{"l":"kuram/foldable/FoldableSyntax$.html#@<<-fffff50e","e":false,"i":"extension [F[_], A, B](foldable: F[A])(implicit evidence$1: Foldable[F])","n":"@<<","t":"@<<: B","d":"kuram.foldable.FoldableSyntax","k":"def","x":""},
{"l":"kuram/foldable/FoldableSyntax$.html#@>>-fffff50e","e":false,"i":"extension [F[_], A, B](foldable: F[A])(implicit evidence$1: Foldable[F])","n":"@>>","t":"@>>: B","d":"kuram.foldable.FoldableSyntax","k":"def","x":""},
{"l":"kuram/kuram.html#","e":false,"i":"","n":"kuram.kuram","t":"kuram.kuram","d":"","k":"package","x":""},
{"l":"kuram/monoid.html#","e":false,"i":"","n":"kuram.monoid","t":"kuram.monoid","d":"","k":"package","x":""},
{"l":"kuram/monoid/instances.html#","e":false,"i":"","n":"kuram.monoid.instances","t":"kuram.monoid.instances","d":"","k":"package","x":""},
{"l":"kuram/monoid/Monoid.html#","e":false,"i":"","n":"Monoid","t":"Monoid[T] extends Semigroup[T]","d":"kuram.monoid","k":"trait","x":""},
{"l":"kuram/monoid/Monoid.html#empty-0","e":false,"i":"","n":"empty","t":"empty: T","d":"kuram.monoid.Monoid","k":"def","x":""},
{"l":"kuram/monoid/Monoid$.html#","e":false,"i":"","n":"Monoid","t":"Monoid","d":"kuram.monoid","k":"object","x":""},
{"l":"kuram/monoid/Monoid$.html#apply-2f1","e":false,"i":"","n":"apply","t":"apply[T](using instance: Monoid[T]): Monoid[T]","d":"kuram.monoid.Monoid","k":"def","x":""},
{"l":"kuram/monoid/MonoidInstances$.html#","e":false,"i":"","n":"MonoidInstances","t":"MonoidInstances","d":"kuram.monoid","k":"object","x":""},
{"l":"kuram/monoid/MonoidInstances$.html#conjuctionBooleanMonoid-0","e":false,"i":"","n":"conjuctionBooleanMonoid","t":"conjuctionBooleanMonoid: conjuctionBooleanMonoid","d":"kuram.monoid.MonoidInstances","k":"given","x":""},
{"l":"kuram/monoid/MonoidInstances$.html#disjunctionBooleanMonoid-0","e":false,"i":"","n":"disjunctionBooleanMonoid","t":"disjunctionBooleanMonoid: disjunctionBooleanMonoid","d":"kuram.monoid.MonoidInstances","k":"given","x":""},
{"l":"kuram/monoid/MonoidInstances$.html#given_Monoid_Int-0","e":false,"i":"","n":"given_Monoid_Int","t":"given_Monoid_Int: given_Monoid_Int","d":"kuram.monoid.MonoidInstances","k":"given","x":""},
{"l":"kuram/monoid/MonoidInstances$.html#given_Monoid_List-c98","e":false,"i":"","n":"given_Monoid_List","t":"given_Monoid_List[A]: given_Monoid_List[A]","d":"kuram.monoid.MonoidInstances","k":"given","x":""},
{"l":"kuram/monoid/MonoidInstances$.html#given_Monoid_Map-fffffcd3","e":false,"i":"","n":"given_Monoid_Map","t":"given_Monoid_Map[K, V : Monoid]: given_Monoid_Map[K, V]","d":"kuram.monoid.MonoidInstances","k":"given","x":""},
{"l":"kuram/monoid/MonoidInstances$.html#given_Monoid_Option-a1d","e":false,"i":"","n":"given_Monoid_Option","t":"given_Monoid_Option[A : Monoid]: given_Monoid_Option[A]","d":"kuram.monoid.MonoidInstances","k":"given","x":""},
{"l":"kuram/monoid/MonoidInstances$.html#given_Monoid_String-0","e":false,"i":"","n":"given_Monoid_String","t":"given_Monoid_String: given_Monoid_String","d":"kuram.monoid.MonoidInstances","k":"given","x":""},
{"l":"kuram/monoid/MonoidInstances$.html#intersectSetMonoid-1e6","e":false,"i":"","n":"intersectSetMonoid","t":"intersectSetMonoid[A]: intersectSetMonoid[A]","d":"kuram.monoid.MonoidInstances","k":"given","x":""},
{"l":"kuram/monoid/MonoidInstances$.html#unionSetMonoid-fffff0b6","e":false,"i":"","n":"unionSetMonoid","t":"unionSetMonoid[A]: unionSetMonoid[A]","d":"kuram.monoid.MonoidInstances","k":"given","x":""},
{"l":"kuram/monoid/MonoidInstances$$conjuctionBooleanMonoid$.html#","e":false,"i":"","n":"conjuctionBooleanMonoid","t":"conjuctionBooleanMonoid extends Monoid[Boolean]","d":"kuram.monoid.MonoidInstances","k":"object","x":""},
{"l":"kuram/monoid/MonoidInstances$$conjuctionBooleanMonoid$.html#combine-b60","e":false,"i":"","n":"combine","t":"combine(a: Boolean, b: Boolean): Boolean","d":"kuram.monoid.MonoidInstances.conjuctionBooleanMonoid","k":"def","x":""},
{"l":"kuram/monoid/MonoidInstances$$conjuctionBooleanMonoid$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: Boolean","d":"kuram.monoid.MonoidInstances.conjuctionBooleanMonoid","k":"def","x":""},
{"l":"kuram/monoid/MonoidInstances$$disjunctionBooleanMonoid$.html#","e":false,"i":"","n":"disjunctionBooleanMonoid","t":"disjunctionBooleanMonoid extends Monoid[Boolean]","d":"kuram.monoid.MonoidInstances","k":"object","x":""},
{"l":"kuram/monoid/MonoidInstances$$disjunctionBooleanMonoid$.html#combine-b60","e":false,"i":"","n":"combine","t":"combine(a: Boolean, b: Boolean): Boolean","d":"kuram.monoid.MonoidInstances.disjunctionBooleanMonoid","k":"def","x":""},
{"l":"kuram/monoid/MonoidInstances$$disjunctionBooleanMonoid$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: Boolean","d":"kuram.monoid.MonoidInstances.disjunctionBooleanMonoid","k":"def","x":""},
{"l":"kuram/monoid/MonoidInstances$$given_Monoid_Int$.html#","e":false,"i":"","n":"given_Monoid_Int","t":"given_Monoid_Int extends Monoid[Int]","d":"kuram.monoid.MonoidInstances","k":"object","x":""},
{"l":"kuram/monoid/MonoidInstances$$given_Monoid_Int$.html#combine-f47","e":false,"i":"","n":"combine","t":"combine(a: Int, b: Int): Int","d":"kuram.monoid.MonoidInstances.given_Monoid_Int","k":"def","x":""},
{"l":"kuram/monoid/MonoidInstances$$given_Monoid_Int$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: Int","d":"kuram.monoid.MonoidInstances.given_Monoid_Int","k":"def","x":""},
{"l":"kuram/monoid/MonoidInstances$$given_Monoid_String$.html#","e":false,"i":"","n":"given_Monoid_String","t":"given_Monoid_String extends Monoid[String]","d":"kuram.monoid.MonoidInstances","k":"object","x":""},
{"l":"kuram/monoid/MonoidInstances$$given_Monoid_String$.html#combine-fffff52f","e":false,"i":"","n":"combine","t":"combine(a: String, b: String): String","d":"kuram.monoid.MonoidInstances.given_Monoid_String","k":"def","x":""},
{"l":"kuram/monoid/MonoidInstances$$given_Monoid_String$.html#empty-0","e":false,"i":"","n":"empty","t":"empty: String","d":"kuram.monoid.MonoidInstances.given_Monoid_String","k":"def","x":""},
{"l":"kuram/semigroup.html#","e":false,"i":"","n":"kuram.semigroup","t":"kuram.semigroup","d":"","k":"package","x":""},
{"l":"kuram/semigroup/instances.html#","e":false,"i":"","n":"kuram.semigroup.instances","t":"kuram.semigroup.instances","d":"","k":"package","x":""},
{"l":"kuram/semigroup/Semigroup.html#","e":false,"i":"","n":"Semigroup","t":"Semigroup[T]","d":"kuram.semigroup","k":"trait","x":""},
{"l":"kuram/semigroup/Semigroup.html#combine-fffffab9","e":false,"i":"","n":"combine","t":"combine(a: T, b: T): T","d":"kuram.semigroup.Semigroup","k":"def","x":""},
{"l":"kuram/semigroup/Semigroup$.html#","e":false,"i":"","n":"Semigroup","t":"Semigroup","d":"kuram.semigroup","k":"object","x":""},
{"l":"kuram/semigroup/Semigroup$.html#apply-fffffb31","e":false,"i":"","n":"apply","t":"apply[T](using instance: Semigroup[T]): Semigroup[T]","d":"kuram.semigroup.Semigroup","k":"def","x":""},
{"l":"kuram/semigroup/SemigroupInstances$.html#","e":false,"i":"","n":"SemigroupInstances","t":"SemigroupInstances","d":"kuram.semigroup","k":"object","x":""},
{"l":"kuram/semigroup/SemigroupInstances$.html#given_Semigroup_Int-0","e":false,"i":"","n":"given_Semigroup_Int","t":"given_Semigroup_Int: given_Semigroup_Int","d":"kuram.semigroup.SemigroupInstances","k":"given","x":""},
{"l":"kuram/semigroup/SemigroupInstances$.html#given_Semigroup_List-fffffb8d","e":false,"i":"","n":"given_Semigroup_List","t":"given_Semigroup_List[A]: given_Semigroup_List[A]","d":"kuram.semigroup.SemigroupInstances","k":"given","x":""},
{"l":"kuram/semigroup/SemigroupInstances$.html#given_Semigroup_String-0","e":false,"i":"","n":"given_Semigroup_String","t":"given_Semigroup_String: given_Semigroup_String","d":"kuram.semigroup.SemigroupInstances","k":"given","x":""},
{"l":"kuram/semigroup/SemigroupInstances$$given_Semigroup_Int$.html#","e":false,"i":"","n":"given_Semigroup_Int","t":"given_Semigroup_Int extends Semigroup[Int]","d":"kuram.semigroup.SemigroupInstances","k":"object","x":""},
{"l":"kuram/semigroup/SemigroupInstances$$given_Semigroup_Int$.html#combine-f47","e":false,"i":"","n":"combine","t":"combine(a: Int, b: Int): Int","d":"kuram.semigroup.SemigroupInstances.given_Semigroup_Int","k":"def","x":""},
{"l":"kuram/semigroup/SemigroupInstances$$given_Semigroup_String$.html#","e":false,"i":"","n":"given_Semigroup_String","t":"given_Semigroup_String extends Semigroup[String]","d":"kuram.semigroup.SemigroupInstances","k":"object","x":""},
{"l":"kuram/semigroup/SemigroupInstances$$given_Semigroup_String$.html#combine-fffff52f","e":false,"i":"","n":"combine","t":"combine(a: String, b: String): String","d":"kuram.semigroup.SemigroupInstances.given_Semigroup_String","k":"def","x":""},
{"l":"kuram/semigroup/SemigroupSyntax$.html#","e":false,"i":"","n":"SemigroupSyntax","t":"SemigroupSyntax","d":"kuram.semigroup","k":"object","x":""},
{"l":"kuram/semigroup/SemigroupSyntax$.html#|+|-fffff176","e":false,"i":"extension [T](a: T)","n":"|+|","t":"|+|(b: T)(using semigroup: Semigroup[T]): T","d":"kuram.semigroup.SemigroupSyntax","k":"def","x":""},
{"l":"kuram/Functor.html#","e":false,"i":"","n":"Functor","t":"Functor[F[_]]","d":"kuram","k":"trait","x":""},
{"l":"kuram/FunctorInstances$.html#","e":false,"i":"","n":"FunctorInstances","t":"FunctorInstances","d":"kuram","k":"object","x":""},
{"l":"kuram/FunctorSyntax$.html#","e":false,"i":"","n":"FunctorSyntax","t":"FunctorSyntax","d":"kuram","k":"object","x":""}];